### ISSUE TITLE
Show how users will benefit from this project

### ISSUE THREAD

**Issue by Henry-Gao-2004** [Tomato-Tigers/TeamForge#14]

**Comment by katyakurchin** [comment]
**Highlighting Potential Users:**

Students:

- Primary users of this program
- Creating a group is difficult and finding a compatible one is even more difficult
- Too many branches of communication to go through.
- Daunting to reach out to people.

Professors:

- Users that need to find methods of facilitating better communication between students
- Need to provide stepping stones without direct involvement

**Benefits:**

Profile building: 

- Users can create a more expansive profile of themselves which can allow others to get a better picture of the type of group member they are and what they are interested in doing during a project.
- Users can expand further on their profile in the case of forgetting to add important skill sets/background/etc. Or in the case of developing new ideas, the user can edit their response.
- Allows specific interests to be tagged.

Organization:

- Each interest will be tagged and there will be mutual tags shown for users. This allows people to easily find people to work with that are compatible with the kind of project they want to do.
- Creates a graph with nodes and edges representing people and their connections which allows for a more concise organization instead of huge blocks of text.
- Edges show mutual interest as well as others who are interested in the same type of project/projects members allowing to make a group from just one person.

Communication:

- All communication is centered in this program. Eliminates the need to hunt down emails/phone numbers or discussion posts on canvas.
- More encouragement to reach out to one another as you can message directly from reading others’ profiles.
